<a href="https://colab.research.google.com/github/arunnivas85/AL_ML/blob/main/Revision_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("This is Numpy Test")

import numpy as np

# a = np.array([1,2,3,4,5])
# print(a)

# z=np.zeros((3,4))
# print(z)

# o=np.ones((2,3))
# print(o)

# ar=np.arange(0,10,2)
# print(ar)

# l= np.linspace(1,10,5)
# print(l)

# r=np.random.randn(3,3)
# print(r)

# print("---------")

# print(a.shape)
# print(a.ndim)  #n dimension
# a.dtype
# a.size


# a = np.array([[1,2,3], [4,5,6], [7,8,9]])
# a[1,2]
# a[0,:]
# a[:,1]
# a[1:,:2]
# a[a>8]

# #     0  1  2
# # 0  [1, 2, 3]
# # 1  [4, 5, 6]
# # 2  [7, 8, 9]


# a=np.array([1,2,3])
# b=np.array([10,20,30])
# c=np.array([9,16,25])

# a+b
# a * 2
# np.sqrt(c)
# np.dot(a,b)  # (1*10) + (2*20) + (3*30)   == 140


# m=np.ones((3,3))
# print(m)
# row=np.array((1,2,3))
# print(row)

# m+row
#   #  [2., 3., 4.],
#   #  [2., 3., 4.],
#   #  [2., 3., 4.]

a = np.array([[1,2,3],[4,5,6]])

#print(a)
np.sum(a)
np.sum(a, axis=0)   # [5, 7, 9]
np.sum(a, axis=1)   # [ 6, 15]
np.mean(a)
np.std(a)
np.argmax(a)

# [1 2 3]
# [4 5 6]

a=np.arange(12)
b=np.arange(14, 26, 2)

# print(a)
print(b)
# a.reshape(3,4)
# a.reshape(4,-1)   #-1 auto interfers and adjust based on divisable
# a.flatten()    # 1D copy
#a.ravel()         # 1D view
# np.vstack(a)
# np.hstack(a)

This is Numpy Test
[14 16 18 20 22 24]
